### ISSUE TITLE
Delete this repo

### ISSUE THREAD

**Issue by mlmorg** [fusionjs/eslint-config-fusion#16]
I don't see the point of having this repo differ from https://github.com/uber-web/uber-eslint/tree/next/packages/eslint-config-uber-universal-stage-3. Should we just delete this one and make the uber-eslint config match what we use here?

**Comment by KevinGrandon** [comment]
Also the import rule, but those could live in the uber-web version.

It just depends if we want to have custom linter rules for fusion apps or not, I could see those being useful and something that we might want to have here.

**Comment by rtsao** [comment]
I think eventually this repo will probably have more specialized rules and configuration tailored for fusion apps. If anything, I feel like we should delete the *other* package.

**Comment by mlmorg** [comment]
It seems like this repo as it stands today could be useful for a lot of things outside of just fusion apps. If we expect this to change then I think we could keep this repo, but it seems like it would make more sense to fold all the changes currently in this repo into `eslint-config-uber-universal-stage-3` and then have this repo simply extend from that with no additional functionality (until the point that we need to be different between fusion apps and, say, fusion plugins or react components or something...).
