### ISSUE TITLE
Remove import/first[absolute-first] in favor of import/order

### ISSUE THREAD

**Issue by KevinGrandon** [fusionjs/eslint-config-fusion#62]
### Type of issue

Feature request

### Description

Remove https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/first.md in favor of https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md.

This will allow for more fine-grained control over import ordering and consistency everywhere.

**Comment by rickyp-uber** [comment]
Oh and if you're enforcing the sort order of imports, may want to include exports in that ordering then
and change import/exports-last to on instead of off (which is it's current value)

**Comment by rickyp-uber** [comment]
About import/first... Jest allows you to mock an import, for example:
```
jest.mock('@uber/web-rpc-redux');
import * as rpcRedux from '@uber/web-rpc-redux';
```

Without adding a eslint-disable for every single one of these cases, is there a more general solution if we keep import/first?

**Comment by KevinGrandon** [comment]
I think we've decided as a team that we only want to go with eslint:recommended and type checking for now. Developers can be more specific with their own rules if they want.

**Comment by rickyp-uber** [comment]
Is there a issue/PR tracking the work to remove the non eslint:recommended rules that have already been added?
