### ISSUE TITLE
Build failing due to new peerDependency for eslint-config-jest

### ISSUE THREAD

**Issue by jasonbarone** [fusionjs/eslint-config-fusion#90]
Hello, I'm using eslint-config-fusion outside of a FusionJS project. The latest patch to add eslint-config-jest is breaking our builds due to the absence of that dependency. To resolve, I've added it manually, but I would consider patch fixing it, and rolling this out on a minor/major instead.

Commit causing issue: https://github.com/fusionjs/eslint-config-fusion/commit/cb2bb2492fea282019b6d7753beef5b3925602b7

**Comment by AlexMSmithCA** [comment]
Thanks for filing this @jasonbarone!  We had not anticipated non-Fusion.js projects using this package.  As a fix, we released [v3.0.2](https://github.com/fusionjs/eslint-config-fusion/releases/tag/v3.0.2) which rolls back this change and [v4.0.0](https://github.com/fusionjs/eslint-config-fusion/releases/tag/v4.0.0) which re-instates it.

I am closing this as resolved.
